-- Remove USE [CINEMA]; e GO

-- Converte PUBLICO para INTEGER
ALTER TABLE public.bilheteriafilmes2024 ALTER COLUMN PUBLICO TYPE INTEGER USING (PUBLICO::INTEGER);


-- Converte REGISTRO_SALA para INTEGER
ALTER TABLE public.bilheteriafilmes2024 ALTER COLUMN REGISTRO_SALA TYPE INTEGER USING (REGISTRO_SALA::INTEGER);


-- Converte REGISTRO_GRUPO_EXIBIDOR para INTEGER
ALTER TABLE public.bilheteriafilmes2024 ALTER COLUMN REGISTRO_GRUPO_EXIBIDOR TYPE INTEGER USING (REGISTRO_GRUPO_EXIBIDOR::INTEGER);


-- Converte REGISTRO_EXIBIDOR para INTEGER
ALTER TABLE public.bilheteriafilmes2024 ALTER COLUMN REGISTRO_EXIBIDOR TYPE INTEGER USING (REGISTRO_EXIBIDOR::INTEGER);


-- Converte REGISTRO_COMPLEXO para INTEGER
ALTER TABLE public.bilheteriafilmes2024 ALTER COLUMN REGISTRO_COMPLEXO TYPE INTEGER USING (REGISTRO_COMPLEXO::INTEGER);


-- Converte NR_PROTOCOLO_ENVIO para BIGINT
ALTER TABLE public.bilheteriafilmes2024 ALTER COLUMN NR_PROTOCOLO_ENVIO TYPE BIGINT USING (NR_PROTOCOLO_ENVIO::BIGINT);


-- Converte DATA_HORA_ENVIO_PROTOCOLO para TIMESTAMP
ALTER TABLE public.bilheteriafilmes2024 ALTER COLUMN DATA_HORA_ENVIO_PROTOCOLO TYPE TIMESTAMP USING (DATA_HORA_ENVIO_PROTOCOLO::TIMESTAMP);

-- Converte REGISTRO_SALA para INTEGER
ALTER TABLE public.salascomplexos ALTER COLUMN REGISTRO_SALA TYPE INTEGER USING (REGISTRO_SALA::INTEGER);


-- Converte DATA_SITUACAO_SALA para DATE
ALTER TABLE public.salascomplexos ALTER COLUMN DATA_SITUACAO_SALA TYPE DATE USING (DATA_SITUACAO_SALA::DATE);


-- Converte DATA_INICIO_FUNCIONAMENTO_SALA para DATE
ALTER TABLE public.salascomplexos ALTER COLUMN DATA_INICIO_FUNCIONAMENTO_SALA TYPE DATE USING (DATA_INICIO_FUNCIONAMENTO_SALA::DATE);


-- Converte ASSENTOS_SALA para INTEGER
ALTER TABLE public.salascomplexos ALTER COLUMN ASSENTOS_SALA TYPE INTEGER USING (ASSENTOS_SALA::INTEGER);


-- Converte ASSENTOS_CADEIRANTES para INTEGER
ALTER TABLE public.salascomplexos ALTER COLUMN ASSENTOS_CADEIRANTES TYPE INTEGER USING (ASSENTOS_CADEIRANTES::INTEGER);


-- Converte ASSENTOS_MOBILIDADE_REDUZIDA para INTEGER
ALTER TABLE public.salascomplexos ALTER COLUMN ASSENTOS_MOBILIDADE_REDUZIDA TYPE INTEGER USING (ASSENTOS_MOBILIDADE_REDUZIDA::INTEGER);


-- Converte ASSENTOS_OBESIDADE para INTEGER
ALTER TABLE public.salascomplexos ALTER COLUMN ASSENTOS_OBESIDADE TYPE INTEGER USING (ASSENTOS_OBESIDADE::INTEGER);


-- Converte REGISTRO_COMPLEXO para INTEGER
ALTER TABLE public.salascomplexos ALTER COLUMN REGISTRO_COMPLEXO TYPE INTEGER USING (REGISTRO_COMPLEXO::INTEGER);


-- Converte DATA_SITUACAO_COMPLEXO para DATE
ALTER TABLE public.salascomplexos ALTER COLUMN DATA_SITUACAO_COMPLEXO TYPE DATE USING (DATA_SITUACAO_COMPLEXO::DATE);


-- Converte REGISTRO_EXIBIDOR para INTEGER
ALTER TABLE public.salascomplexos ALTER COLUMN REGISTRO_EXIBIDOR TYPE INTEGER USING (REGISTRO_EXIBIDOR::INTEGER);
