-- Remove a linha 'USE [CINEMA];' pois você já está conectado ao banco de dados CINEMA no DBeaver.

CREATE TABLE if not exists public.BilheteriaFilmes2024 (
    DATA_EXIBICAO DATE NULL,
    TITULO_ORIGINAL VARCHAR(255) NULL, -- Corrigido para VARCHAR(255) como planejado
    TITULO_BRASIL VARCHAR(255) NULL, -- Corrigido para VARCHAR(255) como planejado
    CPB_ROE VARCHAR(20) NULL, -- Corrigido para VARCHAR(20) como planejado
    PAIS_OBRA VARCHAR(50) NULL, -- Corrigido para VARCHAR(50) como planejado
    REGISTRO_SALA INTEGER NULL, -- Corrigido para INTEGER como planejado
    NOME_SALA VARCHAR(100) NULL, -- Corrigido para VARCHAR(100) como planejado
    PUBLICO INTEGER NULL, -- Corrigido para INTEGER como planejado
    REGISTRO_GRUPO_EXIBIDOR INTEGER NULL, -- Corrigido para INTEGER como planejado
    REGISTRO_EXIBIDOR INTEGER NULL, -- Corrigido para INTEGER como planejado
    REGISTRO_COMPLEXO INTEGER NULL, -- Corrigido para INTEGER como planejado
    MUNICIPIO_SALA_COMPLEXO VARCHAR(100) NULL, -- Corrigido para VARCHAR(100) como planejado
    UF_SALA_COMPLEXO VARCHAR(2) NULL, -- Corrigido para VARCHAR(2) como planejado
    RAZAO_SOCIAL_DISTRIBUIDORA VARCHAR(150) NULL, -- Corrigido para VARCHAR(150) como planejado
    CNPJ_DISTRIBUIDORA VARCHAR(18) NULL, -- Corrigido para VARCHAR(18) como planejado
    NR_PROTOCOLO_ENVIO BIGINT NULL, -- Corrigido para BIGINT como planejado
    DATA_HORA_ENVIO_PROTOCOLO TIMESTAMP NULL -- Corrigido para TIMESTAMP como planejado (ou TIMESTAMPTZ se precisar de fuso horário)
);

CREATE table if not exists public.SalasComplexos (
    NOME_SALA VARCHAR(150) NULL,
    REGISTRO_SALA INTEGER NULL, -- Convertido de INT para INTEGER
    CNPJ_SALA VARCHAR(18) NULL,
    SITUACAO_SALA VARCHAR(50) NULL,
    DATA_SITUACAO_SALA DATE NULL,
    DATA_INICIO_FUNCIONAMENTO_SALA DATE NULL,
    ASSENTOS_SALA INTEGER NULL, -- Convertido de INT para INTEGER
    ASSENTOS_CADEIRANTES INTEGER NULL, -- Convertido de INT para INTEGER
    ASSENTOS_MOBILIDADE_REDUZIDA INTEGER NULL, -- Convertido de INT para INTEGER
    ASSENTOS_OBESIDADE INTEGER NULL, -- Convertido de INT para INTEGER
    ACESSO_ASSENTOS_COM_RAMPA VARCHAR(10) NULL,
    ACESSO_SALA_COM_RAMPA VARCHAR(10) NULL,
    BANHEIROS_ACESSIVEIS VARCHAR(10) NULL,
    NOME_COMPLEXO VARCHAR(150) NULL,
    REGISTRO_COMPLEXO INTEGER NULL, -- Convertido de INT para INTEGER
    SITUACAO_COMPLEXO VARCHAR(50) NULL,
    DATA_SITUACAO_COMPLEXO DATE NULL,
    PAGINA_ELETRONICA_COMPLEXO VARCHAR(255) NULL,
    ENDERECO_COMPLEXO VARCHAR(255) NULL,
    NUMERO_ENDERECO_COMPLEXO VARCHAR(50) NULL,
    COMPLEMENTO_COMPLEXO VARCHAR(100) NULL,
    BAIRRO_COMPLEXO VARCHAR(100) NULL,
    MUNICIPIO_COMPLEXO VARCHAR(100) NULL,
    CEP_COMPLEXO VARCHAR(10) NULL,
    UF_COMPLEXO VARCHAR(2) NULL,
    COMPLEXO_ITINERANTE VARCHAR(10) NULL,
    OPERACAO_USUAL VARCHAR(50) NULL,
    NOME_EXIBIDOR VARCHAR(150) NULL,
    REGISTRO_EXIBIDOR INTEGER NULL, -- Convertido de INT para INTEGER
    CNPJ_EXIBIDOR VARCHAR(18) NULL,
    SITUACAO_EXIBIDOR VARCHAR(50) NULL,
    NOME_GRUPO_EXIBIDOR VARCHAR(150) NULL
);
